### ISSUE TITLE
Node Template not setting

### ISSUE THREAD

**Issue by re-thc** [montel-ig/ui-driver-upcloud#1]
Hi, I added the driver as per the instructions. Tried to create a Node Template picking Singapore and the 2GB option. When I go to edit this template it is not remembered. When I view it it says Location/Size unknown.

**Comment by a-rmz** [comment]
Hey @hc-codersatlas! Thanks again for your comments. 😁 

Please check the [latest](https://github.com/montel-ig/ui-driver-upcloud/releases/tag/1.0.1) version, it is also now live on the [server](https://rancher.montel.fi/upcloud/ui/).

About the `Location`/`Size` unknown, I was checking the Rancher UI code and it's kinda hard-coded that only the "official" (or at least the ones supported by Rancher) drivers have a way to get it.

If you want to dig deeper, take a look at the code of the [node-driver mixin](https://github.com/rancher/ui/blob/11ea8e36d51e8caa05e7b1f4223e3f52a10ef249/lib/shared/addon/mixins/node-driver.js#L39) and the [node template model](https://github.com/rancher/ui/blob/6d75ad47e6da05b48a0f1131bff8b66cf03a0fb8/app/models/nodetemplate.js#L93), maybe that's a good start point. 😉
